# Author: Pedro Estrada
# Email:  pestrada2@miners.utep.edu

CC=gcc
OBJ_S=sinTest
S_SRC=sinTest.c
OBJ=-o
MATH=-lm

all: $(OBJ_S)
$(OBJ_S): $(S_SRC)
	$(CC) $(OBJ) $(OBJ_S) $(S_SRC) $(MATH)
clean:
	rm *.o; rm *.o~; rm *~; rm $(OBJ_C); rm $(OBJ_S);